// Sidebar.js
import React from 'react';
import { Link } from 'react-router-dom';
import './Sidebar.css';

// Sample data for topics
const topics = [
  {
    id: 'cab201',
    name: 'CAB201 - Programming Principles',
    posts: [
      { id: 'programming', title: 'Programming' },
      { id: 'types-and-expressions', title: 'Types and Expressions' },
      { id: 'structured-programming', title: 'Structured Programming' },
      { id: 'functions', title: 'Functions' },
      { id: 'arrays', title: 'Arrays' },
      { id: 'pointers', title: 'Pointers' },
      { id: 'recursion', title: 'Recursion' },
    ],
  },
  {
    id: 'cab202',
    name: 'CAB202 - Algorithms and Complexity',
    posts: [
      { id: 'algorithms', title: 'Algorithms' },
      { id: 'complexity', title: 'Complexity' },
      { id: 'sorting', title: 'Sorting' },
      { id: 'searching', title: 'Searching' },
      { id: 'graphs', title: 'Graphs' },
      { id: 'trees', title: 'Trees' },
      { id: 'dynamic-programming', title: 'Dynamic Programming' },
    ],
  },
  {
    id: 'cab203',
    name: 'CAB203 - Data Structures',
    posts: [
      { id: 'linked-lists', title: 'Linked Lists' },
      { id: 'stacks', title: 'Stacks' },
      { id: 'queues', title: 'Queues' },
      { id: 'hash-tables', title: 'Hash Tables' },
      { id: 'binary-trees', title: 'Binary Trees' },
      { id: 'heaps', title: 'Heaps' },
      { id: 'graphs', title: 'Graphs' },
    ],
  },
  {
    id: 'cab204',
    name: 'CAB204 - Software Engineering',
    posts: [
      { id: 'software-development-life-cycle', title: 'Software Development Life Cycle' },
      { id: 'requirements-engineering', title: 'Requirements Engineering' },
      { id: 'design-patterns', title: 'Design Patterns' },
      { id: 'testing', title: 'Testing' },
      { id: 'maintenance', title: 'Maintenance' },
      { id: 'agile-methodologies', title: 'Agile Methodologies' },
      { id: 'devops', title: 'DevOps' },
    ],
  },
  {
    id: 'cab205',
    name: 'CAB205 - Database Systems',
    posts: [
      { id: 'relational-databases', title: 'Relational Databases' },
      { id: 'sql', title: 'SQL' },
      { id: 'normalization', title: 'Normalization' },
      { id: 'transactions', title: 'Transactions' },
      { id: 'indexes', title: 'Indexes' },
      { id: 'nosql-databases', title: 'NoSQL Databases' },
      { id: 'database-design', title: 'Database Design' },
    ],
  },
  {
    id: 'cab206',
    name: 'CAB206 - Operating Systems',
    posts: [
      { id: 'process-management', title: 'Process Management' },
      { id: 'memory-management', title: 'Memory Management' },
      { id: 'file-systems', title: 'File Systems' },
      { id: 'input-output', title: 'Input/Output' },
      { id: 'concurrency', title: 'Concurrency' },
      { id: 'virtualization', title: 'Virtualization' },
      { id: 'security', title: 'Security' },
    ],
  },
  {
    id: 'cab207',
    name: 'CAB207 - Computer Networks',
    posts: [
      { id: 'network-architecture', title: 'Network Architecture' },
      { id: 'protocols', title: 'Protocols' },
      { id: 'tcp-ip', title: 'TCP/IP' },
      { id: 'network-security', title: 'Network Security' },
      { id: 'wireless-networks', title: 'Wireless Networks' },
      { id: 'cloud-computing', title: 'Cloud Computing' },
      { id: 'network-troubleshooting', title: 'Network Troubleshooting' },
    ],
  },
  {
    id: 'cab208',
    name: 'CAB208 - Web Development',
    posts: [
      { id: 'html-css', title: 'HTML & CSS' },
      { id: 'javascript', title: 'JavaScript' },
      { id: 'react', title: 'React' },
      { id: 'nodejs', title: 'Node.js' },
      { id: 'databases', title: 'Databases' },
      { id: 'web-security', title: 'Web Security' },
      { id: 'api-development', title: 'API Development' },
    ],
  },
  {
    id: 'cab209',
    name: 'CAB209 - Mobile App Development',
    posts: [
      { id: 'android', title: 'Android' },
      { id: 'ios', title: 'iOS' },
      { id: 'flutter', title: 'Flutter' },
      { id: 'react-native', title: 'React Native' },
      { id: 'user-interface', title: 'User Interface' },
      { id: 'user-experience', title: 'User Experience' },
      { id: 'mobile-security', title: 'Mobile Security' },
    ],
  },
  {
    id: 'cab210',
    name: 'CAB210 - Artificial Intelligence',
    posts: [
      { id: 'machine-learning', title: 'Machine Learning' },
      { id: 'deep-learning', title: 'Deep Learning' },
      { id: 'natural-language-processing', title: 'Natural Language Processing' },
      { id: 'computer-vision', title: 'Computer Vision' },
      { id: 'reinforcement-learning', title: 'Reinforcement Learning' },
      { id: 'robotics', title: 'Robotics' },
      { id: 'ai-ethics', title: 'AI Ethics' },
    ],
  },
  {
    id: 'cab211',
    name: 'CAB211 - Cybersecurity',
    posts: [
      { id: 'network-security', title: 'Network Security' },
      { id: 'application-security', title: 'Application Security' },
      { id: 'cryptography', title: 'Cryptography' },
      { id: 'risk-management', title: 'Risk Management' },
      { id: 'incident-response', title: 'Incident Response' },
      { id: 'security-operations', title: 'Security Operations' },
      { id: 'ethical-hacking', title: 'Ethical Hacking' },
    ],
  },
  {
    id: 'cab212',
    name: 'CAB212 - Cloud Computing',
    posts: [
      { id: 'cloud-architecture', title: 'Cloud Architecture' },
      { id: 'aws', title: 'AWS' },
      { id: 'azure', title: 'Azure' },
      { id: 'google-cloud', title: 'Google Cloud' },
      { id: 'cloud-security', title: 'Cloud Security' },
      { id: 'devops-in-the-cloud', title: 'DevOps in the Cloud' },
      { id: 'cloud-migration', title: 'Cloud Migration' },
    ],
  },
  {
    id: 'cab213',
    name: 'CAB213 - Internet of Things',
    posts: [
      { id: 'iot-architecture', title: 'IoT Architecture' },
      { id: 'iot-protocols', title: 'IoT Protocols' },
      { id: 'sensor-networks', title: 'Sensor Networks' },
      { id: 'iot-security', title: 'IoT Security' },
      { id: 'smart-homes', title: 'Smart Homes' },
      { id: 'industrial-iot', title: 'Industrial IoT' },
      { id: 'edge-computing', title: 'Edge Computing' },
    ],
  },
  {
    id: 'cab214',
    name: 'CAB214 - Game Development',
    posts: [
      { id: 'game-design', title: 'Game Design' },
      { id: 'unity', title: 'Unity' },
      { id: 'unreal-engine', title: 'Unreal Engine' },
      { id: '2d-game-development', title: '2D Game Development' },
      { id: '3d-game-development', title: '3D Game Development' },
      { id: 'game-art', title: 'Game Art' },
      { id: 'game-testing', title: 'Game Testing' },
    ],
  },
  {
    id: 'cab215',
    name: 'CAB215 - Human-Computer Interaction',
    posts: [
      { id: 'user-centered-design', title: 'User-Centered Design' },
      { id: 'usability-testing', title: 'Usability Testing' },
      { id: 'interaction-design', title: 'Interaction Design' },
      { id: 'accessible-design', title: 'Accessible Design' },
      { id: 'cognitive-psychology', title: 'Cognitive Psychology' },
      { id: 'interface-design', title: 'Interface Design' },
      { id: 'user-experience-research', title: 'User Experience Research' },
    ],
  },
  {
    id: 'cab216',
    name: 'CAB216 - Software Testing',
    posts: [
      { id: 'test-planning', title: 'Test Planning' },
      { id: 'test-design', title: 'Test Design' },
      { id: 'test-execution', title: 'Test Execution' },
      { id: 'test-automation', title: 'Test Automation' },
      { id: 'defect-management', title: 'Defect Management' },
      { id: 'test-metrics', title: 'Test Metrics' },
      { id: 'test-strategy', title: 'Test Strategy' },
    ],
  },
  {
    id: 'cab217',
    name: 'CAB217 - Data Analytics',
    posts: [
      { id: 'data-exploration', title: 'Data Exploration' },
      { id: 'data-preprocessing', title: 'Data Preprocessing' },
      { id: 'data-visualization', title: 'Data Visualization' },
      { id: 'statistical-analysis', title: 'Statistical Analysis' },
      { id: 'machine-learning', title: 'Machine Learning' },
      { id: 'big-data', title: 'Big Data' },
      { id: 'data-ethics', title: 'Data Ethics' },
    ],
  },
  {
    id: 'cab218',
    name: 'CAB218 - Blockchain Technology',
    posts: [
      { id: 'blockchain-basics', title: 'Blockchain Basics' },
      { id: 'smart-contracts', title: 'Smart Contracts' },
      { id: 'decentralized-applications', title: 'Decentralized Applications' },
      { id: 'consensus-algorithms', title: 'Consensus Algorithms' },
      { id: 'privacy-and-security', title: 'Privacy and Security' },
      { id: 'tokenization', title: 'Tokenization' },
      { id: 'blockchain-use-cases', title: 'Blockchain Use Cases' },
    ],
  },
  {
    id: 'cab219',
    name: 'CAB219 - Quantum Computing',
    posts: [
      { id: 'quantum-mechanics', title: 'Quantum Mechanics' },
      { id: 'quantum-gates', title: 'Quantum Gates' },
      { id: 'quantum-algorithms', title: 'Quantum Algorithms' },
      { id: 'quantum-error-correction', title: 'Quantum Error Correction' },
      { id: 'quantum-simulation', title: 'Quantum Simulation' },
      { id: 'quantum-cryptography', title: 'Quantum Cryptography' },
      { id: 'quantum-computing-applications', title: 'Quantum Computing Applications' },
    ],
  },
  {
    id: 'cab220',
    name: 'CAB220 - Natural Language Processing',
    posts: [
      { id: 'text-preprocessing', title: 'Text Preprocessing' },
      { id: 'text-classification', title: 'Text Classification' },
      { id: 'named-entity-recognition', title: 'Named Entity Recognition' },
      { id: 'sentiment-analysis', title: 'Sentiment Analysis' },
      { id: 'machine-translation', title: 'Machine Translation' },
      { id: 'question-answering', title: 'Question Answering' },
      { id: 'chatbots', title: 'Chatbots' },
    ],
  },
  {
    id: 'cab221',
    name: 'CAB221 - Artificial Neural Networks',
    posts: [
      { id: 'neuron-models', title: 'Neuron Models' },
      { id: 'activation-functions', title: 'Activation Functions' },
      { id: 'backpropagation', title: 'Backpropagation' },
      { id: 'convolutional-neural-networks', title: 'Convolutional Neural Networks' },
      { id: 'recurrent-neural-networks', title: 'Recurrent Neural Networks' },
      { id: 'generative-adversarial-networks', title: 'Generative Adversarial Networks' },
      { id: 'transfer-learning', title: 'Transfer Learning' },
    ],
  },
  {
    id: 'cab222',
    name: 'CAB222 - Data Mining',
    posts: [
      { id: 'data-preparation', title: 'Data Preparation' },
      { id: 'association-rule-mining', title: 'Association Rule Mining' },
      { id: 'classification', title: 'Classification' },
      { id: 'clustering', title: 'Clustering' },
      { id: 'text-mining', title: 'Text Mining' },
      { id: 'web-mining', title: 'Web Mining' },
      { id: 'social-network-analysis', title: 'Social Network Analysis' },
    ],
  },
  {
    id: 'cab223',
    name: 'CAB223 - Computer Vision',
    posts: [
      { id: 'image-processing', title: 'Image Processing' },
      { id: 'feature-extraction', title: 'Feature Extraction' },
      { id: 'object-detection', title: 'Object Detection' },
      { id: 'image-segmentation', title: 'Image Segmentation' },
      { id: 'face-recognition', title: 'Face Recognition' },
      { id: 'image-classification', title: 'Image Classification' },
      { id: 'video-tracking', title: 'Video Tracking' },
    ],
  },
  {
    id: 'cab224',
    name: 'CAB224 - Natural Language Generation',
    posts: [
      { id: 'text-generation-models', title: 'Text Generation Models' },
      { id: 'language-models', title: 'Language Models' },
      { id: 'sequence-to-sequence-models', title: 'Sequence-to-Sequence Models' },
      { id: 'transformer-models', title: 'Transformer Models' },
      { id: 'dialogue-generation', title: 'Dialogue Generation' },
      { id: 'storytelling-ai', title: 'Storytelling AI' },
      { id: 'content-generation', title: 'Content Generation' },
    ],
  },
  {
    id: 'cab225',
    name: 'CAB225 - Reinforcement Learning',
    posts: [
      { id: 'markov-decision-processes', title: 'Markov Decision Processes' },
      { id: 'value-iteration', title: 'Value Iteration' },
      { id: 'policy-iteration', title: 'Policy Iteration' },
      { id: 'q-learning', title: 'Q-Learning' },
      { id: 'deep-q-networks', title: 'Deep Q-Networks' },
      { id: 'actor-critic-methods', title: 'Actor-Critic Methods' },
      { id: 'multi-agent-reinforcement-learning', title: 'Multi-Agent Reinforcement Learning' },
    ],
  },
  {
    id: 'cab226',
    name: 'CAB226 - Cloud Security',
    posts: [
      { id: 'cloud-computing-security', title: 'Cloud Computing Security' },
      { id: 'data-privacy-in-the-cloud', title: 'Data Privacy in the Cloud' },
      { id: 'identity-and-access-management', title: 'Identity and Access Management' },
      { id: 'cloud-encryption', title: 'Cloud Encryption' },
      { id: 'cloud-audit-and-compliance', title: 'Cloud Audit and Compliance' },
      { id: 'cloud-incident-response', title: 'Cloud Incident Response' },
      { id: 'cloud-forensics', title: 'Cloud Forensics' },
    ],
  },
  {
    id: 'cab227',
    name: 'CAB227 - Internet Security',
    posts: [
      { id: 'web-application-security', title: 'Web Application Security' },
      { id: 'network-intrusion-detection', title: 'Network Intrusion Detection' },
      { id: 'malware-analysis', title: 'Malware Analysis' },
      { id: 'vulnerability-assessment', title: 'Vulnerability Assessment' },
      { id: 'incident-response', title: 'Incident Response' },
      { id: 'security-awareness-training', title: 'Security Awareness Training' },
      { id: 'cyber-threat-intelligence', title: 'Cyber Threat Intelligence' },
    ],
  },
  {
    id: 'cab228',
    name: 'CAB228 - Mobile Security',
    posts: [
      { id: 'mobile-application-security', title: 'Mobile Application Security' },
      { id: 'mobile-device-management', title: 'Mobile Device Management' },
      { id: 'secure-mobile-communication', title: 'Secure Mobile Communication' },
      { id: 'mobile-payment-security', title: 'Mobile Payment Security' },
      { id: 'mobile-threat-defense', title: 'Mobile Threat Defense' },
      { id: 'mobile-forensics', title: 'Mobile Forensics' },
      { id: 'mobile-security-policies', title: 'Mobile Security Policies' },
    ],
  },
  {
    id: 'cab229',
    name: 'CAB229 - Network Security',
    posts: [
      { id: 'firewalls', title: 'Firewalls' },
      { id: 'intrusion-detection-systems', title: 'Intrusion Detection Systems' },
      { id: 'virtual-private-networks', title: 'Virtual Private Networks' },
      { id: 'network-access-control', title: 'Network Access Control' },
      { id: 'wireless-security', title: 'Wireless Security' },
      { id: 'network-forensics', title: 'Network Forensics' },
      { id: 'security-information-and-event-management', title: 'Security Information and Event Management' },
    ],
  },
  {
    id: 'cab230',
    name: 'CAB230 - Cryptography',
    posts: [
      { id: 'symmetric-key-encryption', title: 'Symmetric Key Encryption' },
      { id: 'asymmetric-key-encryption', title: 'Asymmetric Key Encryption' },
      { id: 'hash-functions', title: 'Hash Functions' },
      { id: 'digital-signatures', title: 'Digital Signatures' },
      { id: 'public-key-infrastructure', title: 'Public Key Infrastructure' },
      { id: 'cryptanalysis', title: 'Cryptanalysis' },
      { id: 'quantum-cryptography', title: 'Quantum Cryptography' },
    ],
  },
  {
    id: 'cab231',
    name: 'CAB231 - Web Application Development',
    posts: [
      { id: 'web-application-architecture', title: 'Web Application Architecture' },
      { id: 'server-side-programming', title: 'Server-Side Programming' },
      { id: 'client-side-programming', title: 'Client-Side Programming' },
      { id: 'web-application-frameworks', title: 'Web Application Frameworks' },
      { id: 'restful-apis', title: 'RESTful APIs' },
      { id: 'authentication-and-authorization', title: 'Authentication and Authorization' },
      { id: 'web-application-security', title: 'Web Application Security' },
    ],
  },
  {
    id: 'cab232',
    name: 'CAB232 - Mobile Application Development',
    posts: [
      { id: 'mobile-application-architecture', title: 'Mobile Application Architecture' },
      { id: 'native-app-development', title: 'Native App Development' },
      { id: 'hybrid-app-development', title: 'Hybrid App Development' },
      { id: 'cross-platform-app-development', title: 'Cross-Platform App Development' },
      { id: 'mobile-app-user-interface', title: 'Mobile App User Interface' },
      { id: 'mobile-app-testing', title: 'Mobile App Testing' },
      { id: 'mobile-app-publishing', title: 'Mobile App Publishing' },
    ],
  },
  {
    id: 'cab233',
    name: 'CAB233 - Game Design',
    posts: [
      { id: 'game-concept-development', title: 'Game Concept Development' },
      { id: 'game-mechanics', title: 'Game Mechanics' },
      { id: 'level-design', title: 'Level Design' },
      { id: 'game-balancing', title: 'Game Balancing' },
      { id: 'game-aesthetics', title: 'Game Aesthetics' },
      { id: 'game-monetization', title: 'Game Monetization' },
      { id: 'game-publishing', title: 'Game Publishing' },
    ],
  },
  {
    id: 'cab234',
    name: 'CAB234 - User Experience Design',
    posts: [
      { id: 'user-research', title: 'User Research' },
      { id: 'user-personas', title: 'User Personas' },
      { id: 'user-journey-mapping', title: 'User Journey Mapping' },
      { id: 'wireframing', title: 'Wireframing' },
      { id: 'prototyping', title: 'Prototyping' },
      { id: 'usability-testing', title: 'Usability Testing' },
      { id: 'user-feedback', title: 'User Feedback' },
    ],
  },
  {
    id: 'cab235',
    name: 'CAB235 - Software Quality Assurance',
    posts: [
      { id: 'quality-assurance-process', title: 'Quality Assurance Process' },
      { id: 'test-planning', title: 'Test Planning' },
      { id: 'test-design', title: 'Test Design' },
      { id: 'test-execution', title: 'Test Execution' },
      { id: 'defect-tracking', title: 'Defect Tracking' },
      { id: 'test-automation', title: 'Test Automation' },
      { id: 'continuous-testing', title: 'Continuous Testing' },
    ],
  },
  {
    id: 'cab236',
    name: 'CAB236 - Big Data Analytics',
    posts: [
      { id: 'big-data-ecosystem', title: 'Big Data Ecosystem' },
      { id: 'data-warehousing', title: 'Data Warehousing' },
      { id: 'data-mining', title: 'Data Mining' },
      { id: 'predictive-analytics', title: 'Predictive Analytics' },
      { id: 'real-time-analytics', title: 'Real-Time Analytics' },
      { id: 'big-data-visualization', title: 'Big Data Visualization' },
      { id: 'data-lakes', title: 'Data Lakes' },
    ],
  },
  {
    id: 'cab237',
    name: 'CAB237 - Blockchain Applications',
    posts: [
      { id: 'supply-chain-management', title: 'Supply Chain Management' },
      { id: 'identity-management', title: 'Identity Management' },
      { id: 'voting-systems', title: 'Voting Systems' },
      { id: 'intellectual-property', title: 'Intellectual Property' },
      { id: 'healthcare', title: 'Healthcare' },
      { id: 'finance', title: 'Finance' },
      { id: 'real-estate', title: 'Real Estate' },
    ],
  },
  {
    id: 'cab238',
    name: 'CAB238 - Quantum Algorithms',
    posts: [
      { id: 'quantum-fourier-transform', title: 'Quantum Fourier Transform' },
      { id: 'grover-algorithm', title: 'Grover Algorithm' },
      { id: 'shor-algorithm', title: 'Shor Algorithm' },
      { id: 'quantum-walks', title: 'Quantum Walks' },
      { id: 'quantum-error-correction', title: 'Quantum Error Correction' },
      { id: 'quantum-simulation', title: 'Quantum Simulation' },
      { id: 'quantum-machine-learning', title: 'Quantum Machine Learning' },
    ],
  },
  {
    id: 'cab239',
    name: 'CAB239 - Natural Language Understanding',
    posts: [
      { id: 'word-embeddings', title: 'Word Embeddings' },
      { id: 'semantic-role-labeling', title: 'Semantic Role Labeling' },
      { id: 'coreference-resolution', title: 'Coreference Resolution' },
      { id: 'text-summarization', title: 'Text Summarization' },
      { id: 'question-answering-systems', title: 'Question Answering Systems' },
      { id: 'dialogue-systems', title: 'Dialogue Systems' },
      { id: 'natural-language-generation', title: 'Natural Language Generation' },
    ],
  },
];

// Sidebar component
const Sidebar = () => (
  <div className="sidebar">
    <h2>Topics</h2>
    <ul>
      {topics.map(topic => (
        <li key={topic.id} className="topic-box">
          <Link to={`/topic/${topic.id}`} className="topic-link">{topic.name}</Link>
        </li>
      ))}
    </ul>
  </div>
);

export default Sidebar;
